
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Notebook notebook1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.HBox hbox2;

	private global::Gtk.HBox hbox3;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.NodeView nodeview1;

	private global::Gtk.VBox vbox1;

	private global::Gtk.Label label9;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hbox9;

	private global::Gtk.Label label10;

	private global::Gtk.ComboBox comboboxEvidencija;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Label label5;

	private global::Gtk.Entry entry1;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Label label6;

	private global::Gtk.Entry entry2;

	private global::Gtk.VBox vbox3;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Label label7;

	private global::Gtk.Entry entry3;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Label label8;

	private global::Gtk.ComboBoxEntry comboboxentryTip;

	private global::Gtk.HBox hbox8;

	private global::Gtk.Button button2;

	private global::Gtk.Label label1;

	private global::Gtk.VBox vbox11;

	private global::Gtk.HBox hbox12;

	private global::Gtk.Label label11;

	private global::Gtk.Entry entry4;

	private global::Gtk.Button button6;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.NodeView nodeview2;

	private global::Gtk.Label label2;

	private global::Gtk.VBox vbox12;

	private global::Gtk.HBox hbox25;

	private global::Gtk.Label label21;

	private global::Gtk.HBox hbox26;

	private global::Gtk.Entry entry5;

	private global::Gtk.HBox hbox14;

	private global::Gtk.Label label23;

	private global::Gtk.Entry entry6;

	private global::Gtk.Button button7;

	private global::Gtk.ScrolledWindow GtkScrolledWindow3;

	private global::Gtk.NodeView nodeview4;

	private global::Gtk.Label label3;

	private global::Gtk.HBox hbox10;

	private global::Gtk.VBox vbox4;

	private global::Gtk.ScrolledWindow GtkScrolledWindow2;

	private global::Gtk.NodeView nodeview3;

	private global::Gtk.VBox vbox6;

	private global::Gtk.VBox vbox7;

	private global::Gtk.VBox vbox5;

	private global::Gtk.Label label12;

	private global::Gtk.HBox hbox13;

	private global::Gtk.Label label20;

	private global::Gtk.Label label22;

	private global::Gtk.HBox hbox17;

	private global::Gtk.Label label13;

	private global::Gtk.Entry entry7;

	private global::Gtk.HBox hbox18;

	private global::Gtk.Label label14;

	private global::Gtk.Entry entry8;

	private global::Gtk.VBox vbox8;

	private global::Gtk.VBox vbox10;

	private global::Gtk.HBox hbox19;

	private global::Gtk.Label label15;

	private global::Gtk.Entry entry9;

	private global::Gtk.HBox hbox20;

	private global::Gtk.Label label16;

	private global::Gtk.Entry entry10;

	private global::Gtk.HBox hbox21;

	private global::Gtk.Label label17;

	private global::Gtk.Entry entry11;

	private global::Gtk.HBox hbox16;

	private global::Gtk.Button button5;

	private global::Gtk.HBox hbox11;

	private global::Gtk.Button button1;

	private global::Gtk.VBox vbox9;

	private global::Gtk.Label label18;

	private global::Gtk.HBox hbox22;

	private global::Gtk.Label label19;

	private global::Gtk.ComboBox comboboxOdaberiRadnika;

	private global::Gtk.HBox hbox15;

	private global::Gtk.Button button4;

	private global::Gtk.Label label4;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Evidencija radnog vremena");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.notebook1 = new global::Gtk.Notebook();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 2;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.nodeview1 = new global::Gtk.NodeView();
		this.nodeview1.CanFocus = true;
		this.nodeview1.Name = "nodeview1";
		this.GtkScrolledWindow.Add(this.nodeview1);
		this.hbox3.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.GtkScrolledWindow]));
		w2.Position = 0;
		this.hbox2.Add(this.hbox3);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.hbox3]));
		w3.Position = 0;
		this.hbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox2]));
		w4.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.Ypad = 7;
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Novi unos:");
		this.vbox1.Add(this.label9);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label9]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label();
		this.label10.Name = "label10";
		this.hbox9.Add(this.label10);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label10]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		w6.Padding = ((uint)(10));
		// Container child hbox9.Gtk.Box+BoxChild
		this.comboboxEvidencija = global::Gtk.ComboBox.NewText();
		this.comboboxEvidencija.WidthRequest = 200;
		this.comboboxEvidencija.Name = "comboboxEvidencija";
		this.hbox9.Add(this.comboboxEvidencija);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.comboboxEvidencija]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		w7.Padding = ((uint)(112));
		this.vbox2.Add(this.hbox9);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox9]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.Ypad = 7;
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Datum:");
		this.hbox4.Add(this.label5);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label5]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		w9.Padding = ((uint)(20));
		// Container child hbox4.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry();
		this.entry1.WidthRequest = 200;
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.Text = global::Mono.Unix.Catalog.GetString("d/m/y");
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.hbox4.Add(this.entry1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.entry1]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		w10.Padding = ((uint)(52));
		this.vbox2.Add(this.hbox4);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.Ypad = 7;
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Početak rada:");
		this.hbox5.Add(this.label6);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label6]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		w12.Padding = ((uint)(20));
		// Container child hbox5.Gtk.Box+BoxChild
		this.entry2 = new global::Gtk.Entry();
		this.entry2.WidthRequest = 200;
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '●';
		this.hbox5.Add(this.entry2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.entry2]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		w13.Padding = ((uint)(20));
		this.vbox2.Add(this.hbox5);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox5]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		this.vbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.Ypad = 7;
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Kraj rada:");
		this.hbox6.Add(this.label7);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label7]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		w16.Padding = ((uint)(20));
		// Container child hbox6.Gtk.Box+BoxChild
		this.entry3 = new global::Gtk.Entry();
		this.entry3.WidthRequest = 200;
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '●';
		this.hbox6.Add(this.entry3);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.entry3]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		w17.Padding = ((uint)(42));
		this.vbox3.Add(this.hbox6);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox6]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.Ypad = 7;
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Tip:");
		this.hbox7.Add(this.label8);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label8]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		w19.Padding = ((uint)(20));
		// Container child hbox7.Gtk.Box+BoxChild
		this.comboboxentryTip = global::Gtk.ComboBoxEntry.NewText();
		this.comboboxentryTip.WidthRequest = 200;
		this.comboboxentryTip.Name = "comboboxentryTip";
		this.hbox7.Add(this.comboboxentryTip);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.comboboxentryTip]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		w20.Padding = ((uint)(72));
		this.vbox3.Add(this.hbox7);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox7]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button();
		this.button2.WidthRequest = 100;
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("Spremi");
		this.hbox8.Add(this.button2);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.button2]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		w22.Padding = ((uint)(120));
		this.vbox3.Add(this.hbox8);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox8]));
		w23.Position = 2;
		w23.Expand = false;
		w23.Fill = false;
		this.vbox1.Add(this.vbox3);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox3]));
		w24.Position = 2;
		w24.Expand = false;
		w24.Fill = false;
		this.hbox1.Add(this.vbox1);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
		w25.Position = 1;
		w25.Expand = false;
		w25.Fill = false;
		this.notebook1.Add(this.hbox1);
		// Notebook tab
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("     UNOS U EVIDENCIJU   ");
		this.notebook1.SetTabLabel(this.hbox1, this.label1);
		this.label1.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox11 = new global::Gtk.VBox();
		this.vbox11.Name = "vbox11";
		this.vbox11.Spacing = 6;
		// Container child vbox11.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.label11.Ypad = 10;
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Unesi datum: ");
		this.hbox12.Add(this.label11);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.label11]));
		w27.Position = 0;
		w27.Expand = false;
		w27.Fill = false;
		w27.Padding = ((uint)(40));
		// Container child hbox12.Gtk.Box+BoxChild
		this.entry4 = new global::Gtk.Entry();
		this.entry4.WidthRequest = 200;
		this.entry4.CanFocus = true;
		this.entry4.Name = "entry4";
		this.entry4.IsEditable = true;
		this.entry4.InvisibleChar = '●';
		this.hbox12.Add(this.entry4);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.entry4]));
		w28.Position = 1;
		w28.Expand = false;
		w28.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button();
		this.button6.WidthRequest = 70;
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("Pretraži");
		this.hbox12.Add(this.button6);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.button6]));
		w29.Position = 2;
		w29.Expand = false;
		w29.Fill = false;
		this.vbox11.Add(this.hbox12);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hbox12]));
		w30.Position = 0;
		w30.Expand = false;
		w30.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.nodeview2 = new global::Gtk.NodeView();
		this.nodeview2.CanFocus = true;
		this.nodeview2.Name = "nodeview2";
		this.GtkScrolledWindow1.Add(this.nodeview2);
		this.vbox11.Add(this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.GtkScrolledWindow1]));
		w32.Position = 1;
		this.notebook1.Add(this.vbox11);
		global::Gtk.Notebook.NotebookChild w33 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox11]));
		w33.Position = 1;
		// Notebook tab
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("   DNEVNA EVIDENCIJA");
		this.notebook1.SetTabLabel(this.vbox11, this.label2);
		this.label2.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox12 = new global::Gtk.VBox();
		this.vbox12.Name = "vbox12";
		this.vbox12.Spacing = 6;
		// Container child vbox12.Gtk.Box+BoxChild
		this.hbox25 = new global::Gtk.HBox();
		this.hbox25.Name = "hbox25";
		this.hbox25.Spacing = 6;
		// Container child hbox25.Gtk.Box+BoxChild
		this.label21 = new global::Gtk.Label();
		this.label21.Name = "label21";
		this.label21.Ypad = 10;
		this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("OD");
		this.hbox25.Add(this.label21);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.label21]));
		w34.Position = 0;
		w34.Expand = false;
		w34.Fill = false;
		w34.Padding = ((uint)(40));
		// Container child hbox25.Gtk.Box+BoxChild
		this.hbox26 = new global::Gtk.HBox();
		this.hbox26.Name = "hbox26";
		this.hbox26.Spacing = 6;
		// Container child hbox26.Gtk.Box+BoxChild
		this.entry5 = new global::Gtk.Entry();
		this.entry5.WidthRequest = 200;
		this.entry5.CanFocus = true;
		this.entry5.Name = "entry5";
		this.entry5.IsEditable = true;
		this.entry5.InvisibleChar = '●';
		this.hbox26.Add(this.entry5);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.entry5]));
		w35.Position = 0;
		w35.Expand = false;
		w35.Fill = false;
		// Container child hbox26.Gtk.Box+BoxChild
		this.hbox14 = new global::Gtk.HBox();
		this.hbox14.Name = "hbox14";
		this.hbox14.Spacing = 6;
		// Container child hbox14.Gtk.Box+BoxChild
		this.label23 = new global::Gtk.Label();
		this.label23.Name = "label23";
		this.label23.LabelProp = global::Mono.Unix.Catalog.GetString("DO");
		this.hbox14.Add(this.label23);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.label23]));
		w36.Position = 0;
		w36.Expand = false;
		w36.Fill = false;
		w36.Padding = ((uint)(40));
		// Container child hbox14.Gtk.Box+BoxChild
		this.entry6 = new global::Gtk.Entry();
		this.entry6.WidthRequest = 200;
		this.entry6.CanFocus = true;
		this.entry6.Name = "entry6";
		this.entry6.IsEditable = true;
		this.entry6.InvisibleChar = '●';
		this.hbox14.Add(this.entry6);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.entry6]));
		w37.Position = 1;
		w37.Expand = false;
		w37.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.button7 = new global::Gtk.Button();
		this.button7.WidthRequest = 70;
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString("Odaberi");
		this.hbox14.Add(this.button7);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.button7]));
		w38.Position = 2;
		w38.Expand = false;
		w38.Fill = false;
		w38.Padding = ((uint)(40));
		this.hbox26.Add(this.hbox14);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.hbox14]));
		w39.Position = 1;
		this.hbox25.Add(this.hbox26);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.hbox26]));
		w40.Position = 1;
		this.vbox12.Add(this.hbox25);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.hbox25]));
		w41.Position = 0;
		w41.Expand = false;
		w41.Fill = false;
		// Container child vbox12.Gtk.Box+BoxChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.nodeview4 = new global::Gtk.NodeView();
		this.nodeview4.CanFocus = true;
		this.nodeview4.Name = "nodeview4";
		this.GtkScrolledWindow3.Add(this.nodeview4);
		this.vbox12.Add(this.GtkScrolledWindow3);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.GtkScrolledWindow3]));
		w43.Position = 1;
		this.notebook1.Add(this.vbox12);
		global::Gtk.Notebook.NotebookChild w44 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox12]));
		w44.Position = 2;
		// Notebook tab
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("VIŠEDNEVNI PREGLED");
		this.notebook1.SetTabLabel(this.vbox12, this.label3);
		this.label3.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.hbox10 = new global::Gtk.HBox();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.nodeview3 = new global::Gtk.NodeView();
		this.nodeview3.CanFocus = true;
		this.nodeview3.Name = "nodeview3";
		this.GtkScrolledWindow2.Add(this.nodeview3);
		this.vbox4.Add(this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.GtkScrolledWindow2]));
		w46.Position = 0;
		this.hbox10.Add(this.vbox4);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.vbox4]));
		w47.Position = 0;
		// Container child hbox10.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.label12 = new global::Gtk.Label();
		this.label12.Name = "label12";
		this.label12.Ypad = 20;
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Unos novog radnika");
		this.vbox5.Add(this.label12);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.label12]));
		w48.Position = 0;
		w48.Expand = false;
		w48.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.label20 = new global::Gtk.Label();
		this.label20.Name = "label20";
		this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("Id radnika");
		this.hbox13.Add(this.label20);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.label20]));
		w49.Position = 0;
		w49.Expand = false;
		w49.Fill = false;
		w49.Padding = ((uint)(40));
		// Container child hbox13.Gtk.Box+BoxChild
		this.label22 = new global::Gtk.Label();
		this.label22.Name = "label22";
		this.label22.LabelProp = global::Mono.Unix.Catalog.GetString("-");
		this.hbox13.Add(this.label22);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.label22]));
		w50.Position = 1;
		w50.Expand = false;
		w50.Fill = false;
		w50.Padding = ((uint)(40));
		this.vbox5.Add(this.hbox13);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox13]));
		w51.Position = 1;
		w51.Expand = false;
		w51.Fill = false;
		this.vbox7.Add(this.vbox5);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.vbox5]));
		w52.Position = 0;
		w52.Expand = false;
		w52.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox17 = new global::Gtk.HBox();
		this.hbox17.Name = "hbox17";
		this.hbox17.Spacing = 6;
		// Container child hbox17.Gtk.Box+BoxChild
		this.label13 = new global::Gtk.Label();
		this.label13.WidthRequest = 120;
		this.label13.Name = "label13";
		this.label13.Xpad = 10;
		this.label13.Ypad = 10;
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Ime i prezime");
		this.hbox17.Add(this.label13);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.label13]));
		w53.Position = 0;
		w53.Expand = false;
		w53.Fill = false;
		// Container child hbox17.Gtk.Box+BoxChild
		this.entry7 = new global::Gtk.Entry();
		this.entry7.WidthRequest = 0;
		this.entry7.CanFocus = true;
		this.entry7.Name = "entry7";
		this.entry7.IsEditable = true;
		this.entry7.InvisibleChar = '●';
		this.hbox17.Add(this.entry7);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.entry7]));
		w54.Position = 1;
		w54.Expand = false;
		w54.Fill = false;
		this.vbox7.Add(this.hbox17);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox17]));
		w55.Position = 1;
		w55.Expand = false;
		w55.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox18 = new global::Gtk.HBox();
		this.hbox18.Name = "hbox18";
		this.hbox18.Spacing = 6;
		// Container child hbox18.Gtk.Box+BoxChild
		this.label14 = new global::Gtk.Label();
		this.label14.WidthRequest = 120;
		this.label14.Name = "label14";
		this.label14.Xpad = 10;
		this.label14.Ypad = 10;
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("OIB");
		this.hbox18.Add(this.label14);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.label14]));
		w56.Position = 0;
		w56.Expand = false;
		w56.Fill = false;
		// Container child hbox18.Gtk.Box+BoxChild
		this.entry8 = new global::Gtk.Entry();
		this.entry8.CanFocus = true;
		this.entry8.Name = "entry8";
		this.entry8.IsEditable = true;
		this.entry8.InvisibleChar = '●';
		this.hbox18.Add(this.entry8);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.entry8]));
		w57.Position = 1;
		w57.Expand = false;
		w57.Fill = false;
		this.vbox7.Add(this.hbox18);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox18]));
		w58.Position = 2;
		w58.Expand = false;
		w58.Fill = false;
		this.vbox6.Add(this.vbox7);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.vbox7]));
		w59.Position = 0;
		w59.Expand = false;
		w59.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.vbox8 = new global::Gtk.VBox();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.vbox10 = new global::Gtk.VBox();
		this.vbox10.Name = "vbox10";
		this.vbox10.Spacing = 6;
		// Container child vbox10.Gtk.Box+BoxChild
		this.hbox19 = new global::Gtk.HBox();
		this.hbox19.Name = "hbox19";
		this.hbox19.Spacing = 6;
		// Container child hbox19.Gtk.Box+BoxChild
		this.label15 = new global::Gtk.Label();
		this.label15.WidthRequest = 120;
		this.label15.Name = "label15";
		this.label15.Xpad = 10;
		this.label15.Ypad = 10;
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Datum zaposlenja");
		this.hbox19.Add(this.label15);
		global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.label15]));
		w60.Position = 0;
		w60.Expand = false;
		w60.Fill = false;
		// Container child hbox19.Gtk.Box+BoxChild
		this.entry9 = new global::Gtk.Entry();
		this.entry9.CanFocus = true;
		this.entry9.Name = "entry9";
		this.entry9.Text = global::Mono.Unix.Catalog.GetString("d/m/y");
		this.entry9.IsEditable = true;
		this.entry9.InvisibleChar = '●';
		this.hbox19.Add(this.entry9);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.entry9]));
		w61.Position = 1;
		w61.Expand = false;
		w61.Fill = false;
		this.vbox10.Add(this.hbox19);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox19]));
		w62.Position = 0;
		w62.Expand = false;
		w62.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.hbox20 = new global::Gtk.HBox();
		this.hbox20.Name = "hbox20";
		this.hbox20.Spacing = 6;
		// Container child hbox20.Gtk.Box+BoxChild
		this.label16 = new global::Gtk.Label();
		this.label16.WidthRequest = 120;
		this.label16.Name = "label16";
		this.label16.Xpad = 10;
		this.label16.Ypad = 10;
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("Radno mjesto");
		this.hbox20.Add(this.label16);
		global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.label16]));
		w63.Position = 0;
		w63.Expand = false;
		w63.Fill = false;
		// Container child hbox20.Gtk.Box+BoxChild
		this.entry10 = new global::Gtk.Entry();
		this.entry10.CanFocus = true;
		this.entry10.Name = "entry10";
		this.entry10.IsEditable = true;
		this.entry10.InvisibleChar = '●';
		this.hbox20.Add(this.entry10);
		global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.entry10]));
		w64.Position = 1;
		w64.Expand = false;
		w64.Fill = false;
		this.vbox10.Add(this.hbox20);
		global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox20]));
		w65.Position = 1;
		w65.Expand = false;
		w65.Fill = false;
		this.vbox8.Add(this.vbox10);
		global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.vbox10]));
		w66.Position = 0;
		w66.Expand = false;
		w66.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox21 = new global::Gtk.HBox();
		this.hbox21.Name = "hbox21";
		this.hbox21.Spacing = 6;
		// Container child hbox21.Gtk.Box+BoxChild
		this.label17 = new global::Gtk.Label();
		this.label17.WidthRequest = 120;
		this.label17.Name = "label17";
		this.label17.Xpad = 10;
		this.label17.Ypad = 10;
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("Odjel");
		this.hbox21.Add(this.label17);
		global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.label17]));
		w67.Position = 0;
		w67.Expand = false;
		w67.Fill = false;
		// Container child hbox21.Gtk.Box+BoxChild
		this.entry11 = new global::Gtk.Entry();
		this.entry11.CanFocus = true;
		this.entry11.Name = "entry11";
		this.entry11.IsEditable = true;
		this.entry11.InvisibleChar = '●';
		this.hbox21.Add(this.entry11);
		global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.entry11]));
		w68.Position = 1;
		w68.Expand = false;
		w68.Fill = false;
		this.vbox8.Add(this.hbox21);
		global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox21]));
		w69.Position = 1;
		w69.Expand = false;
		w69.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox16 = new global::Gtk.HBox();
		this.hbox16.Name = "hbox16";
		this.hbox16.Spacing = 6;
		// Container child hbox16.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("Unesi u bazu");
		this.hbox16.Add(this.button5);
		global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.button5]));
		w70.Position = 1;
		w70.Fill = false;
		// Container child hbox16.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.WidthRequest = 65;
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Izmijeni ");
		this.hbox11.Add(this.button1);
		global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.button1]));
		w71.Position = 0;
		w71.Fill = false;
		this.hbox16.Add(this.hbox11);
		global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.hbox11]));
		w72.Position = 2;
		w72.Padding = ((uint)(10));
		this.vbox8.Add(this.hbox16);
		global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox16]));
		w73.Position = 2;
		w73.Expand = false;
		w73.Fill = false;
		this.vbox6.Add(this.vbox8);
		global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.vbox8]));
		w74.Position = 1;
		w74.Expand = false;
		w74.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.vbox9 = new global::Gtk.VBox();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.label18 = new global::Gtk.Label();
		this.label18.Name = "label18";
		this.label18.Ypad = 20;
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("Brisanje radnika iz baze");
		this.vbox9.Add(this.label18);
		global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.label18]));
		w75.Position = 0;
		w75.Expand = false;
		w75.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hbox22 = new global::Gtk.HBox();
		this.hbox22.Name = "hbox22";
		this.hbox22.Spacing = 6;
		// Container child hbox22.Gtk.Box+BoxChild
		this.label19 = new global::Gtk.Label();
		this.label19.Name = "label19";
		this.label19.Xpad = 10;
		this.label19.Ypad = 10;
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("Odaberi radnika");
		this.hbox22.Add(this.label19);
		global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.label19]));
		w76.Position = 0;
		w76.Expand = false;
		w76.Fill = false;
		// Container child hbox22.Gtk.Box+BoxChild
		this.comboboxOdaberiRadnika = global::Gtk.ComboBox.NewText();
		this.comboboxOdaberiRadnika.WidthRequest = 200;
		this.comboboxOdaberiRadnika.Name = "comboboxOdaberiRadnika";
		this.hbox22.Add(this.comboboxOdaberiRadnika);
		global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.comboboxOdaberiRadnika]));
		w77.Position = 1;
		w77.Expand = false;
		w77.Fill = false;
		w77.Padding = ((uint)(50));
		this.vbox9.Add(this.hbox22);
		global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox22]));
		w78.Position = 1;
		w78.Expand = false;
		w78.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hbox15 = new global::Gtk.HBox();
		this.hbox15.Name = "hbox15";
		this.hbox15.Spacing = 6;
		// Container child hbox15.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("Briši iz baze");
		this.hbox15.Add(this.button4);
		global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.button4]));
		w79.Position = 1;
		w79.Fill = false;
		this.vbox9.Add(this.hbox15);
		global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox15]));
		w80.Position = 2;
		w80.Expand = false;
		w80.Fill = false;
		this.vbox6.Add(this.vbox9);
		global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.vbox9]));
		w81.Position = 2;
		w81.Expand = false;
		w81.Fill = false;
		this.hbox10.Add(this.vbox6);
		global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.vbox6]));
		w82.Position = 1;
		w82.Expand = false;
		w82.Fill = false;
		this.notebook1.Add(this.hbox10);
		global::Gtk.Notebook.NotebookChild w83 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.hbox10]));
		w83.Position = 3;
		// Notebook tab
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("UNOS RADNIKA");
		this.notebook1.SetTabLabel(this.hbox10, this.label4);
		this.label4.ShowAll();
		this.Add(this.notebook1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 947;
		this.DefaultHeight = 688;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button2.Clicked += new global::System.EventHandler(this.SpremiKorisnika);
		this.button6.Clicked += new global::System.EventHandler(this.OnPretrazi);
		this.button7.Clicked += new global::System.EventHandler(this.OnOdaberi);
		this.button5.Clicked += new global::System.EventHandler(this.SpremiRadnika);
		this.button1.Clicked += new global::System.EventHandler(this.IzmijeniPodatkeRadnika);
		this.button4.Clicked += new global::System.EventHandler(this.IzbrisiRadnika);
	}
}
